export const sectionNames = [
  "large_rows",
  "categories",
  "customers",
  "employee_territories",
  "employees",
  "order_details",
  "orders",
  "products",
  "regions",
  "shippers",
  "suppliers",
  "territories",
];

export const sectionInfo = [
  {
    large_rows: [
      "customerID",
      "companyName",
      "contactName",
      "contactTitle",
      "address",
      "city",
      "region",
      "postalCode",
      "country",
      "phone",
      "fax",
      "FIELD12",
      "FIELD13",
      "FIELD14",
      "FIELD15",
      "FIELD16",
      "FIELD17",
      "FIELD18",
      "FIELD19",
      "FIELD20",
      "FIELD21",
    ],
    categories: ["categoryID", "categoryName", "description", "picture"],
    customers: [
      "customerID",
      "companyName",
      "contactName",
      "contactTitle",
      "address",
      "city",
      "region",
      "postalCode",
      "country",
      "phone",
      "fax",
    ],
    employee_territories: ["employeeID", "territoryID"],
    employees: ["employeeID", "lastName", "firstName"],
    order_details: ["orderID", "productID", "unitPrice", "quantity", "discount"],
    orders: [],
    products: [],
    regions: [],
    shippers: [],
    suppliers: [],
    territories: [],
  },
];
